# Generated by Django 2.2 on 2019-10-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '帮助',
                'verbose_name_plural': '帮助文档',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('top', models.BooleanField(default=False, verbose_name='是否置顶')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻列表',
            },
        ),
    ]
