# Generated by Django 2.2 on 2019-10-17 01:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_auto_20191017_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='内容'),
        ),
    ]
