# Generated by Django 2.2 on 2019-10-17 02:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_auto_20191017_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='内容'),
        ),
    ]
