# Generated by Django 2.2 on 2019-10-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='money',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='预约费用'),
        ),
    ]
