# Generated by Django 2.2 on 2019-10-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='money',
            field=models.IntegerField(blank=True, null=True, verbose_name='预约费用'),
        ),
    ]
