# Generated by Django 2.2 on 2019-10-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20191022_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='money',
        ),
    ]
