# Generated by Django 2.2.2 on 2019-06-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('expain_text', models.CharField(max_length=200)),
                ('modify_time', models.DateTimeField(verbose_name='modify time')),
            ],
        ),
    ]
