# Generated by Django 2.2 on 2019-10-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_parameter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='expain_text',
            new_name='desc',
        ),
    ]
