# Generated by Django 2.2 on 2019-12-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parameter', '0002_auto_20191021_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
