# Generated by Django 2.2 on 2019-10-16 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='充值时间')),
                ('money', models.IntegerField(verbose_name='充值金额')),
                ('rest_money', models.IntegerField(verbose_name='剩余金额')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '充值',
                'verbose_name_plural': '充值列表',
            },
        ),
        migrations.CreateModel(
            name='Chargetype',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类型名称')),
                ('value', models.IntegerField(verbose_name='扣费方式，*元/小时')),
            ],
            options={
                'verbose_name': '充值类型',
                'verbose_name_plural': '充值类型列表',
            },
        ),
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类型名称')),
                ('value', models.IntegerField(verbose_name='加班费单价（维护），*元/小时')),
            ],
            options={
                'verbose_name': '消费类型',
                'verbose_name_plural': '消费类型列表',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='消费时间')),
                ('money', models.IntegerField(verbose_name='消费金额')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointment.Appointment', verbose_name='预约记录')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Charge', verbose_name='充值记录')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.PayType', verbose_name='类型')),
            ],
            options={
                'verbose_name': '充值',
                'verbose_name_plural': '充值列表',
            },
        ),
        migrations.AddField(
            model_name='charge',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Chargetype', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='charge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='申请用户'),
        ),
    ]
