# Generated by Django 2.2 on 2019-10-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191016_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chargetype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pay',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paytype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
