# Generated by Django 2.2 on 2019-10-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191016_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': '消费', 'verbose_name_plural': '消费列表'},
        ),
    ]
