# Generated by Django 2.2 on 2019-10-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20191016_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointment.Appointment', verbose_name='预约记录'),
        ),
    ]
