# Generated by Django 2.2 on 2019-10-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20191016_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='充值时间'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='消费时间'),
        ),
    ]
