# Generated by Django 2.2 on 2019-10-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20191017_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='rest_money',
            field=models.IntegerField(verbose_name='剩余金额'),
        ),
    ]
