# Generated by Django 2.2 on 2019-10-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191021_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.Appointment', verbose_name='预约记录'),
        ),
    ]
