# Generated by Django 2.2 on 2019-10-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20191024_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='overtime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('on', models.BooleanField(default=True, verbose_name='是否加班日')),
            ],
        ),
    ]
