# Generated by Django 2.2 on 2019-11-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_overtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtime',
            options={'verbose_name': '加班日期', 'verbose_name_plural': '加班日期表'},
        ),
        migrations.AddField(
            model_name='charge',
            name='contract',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='合同编号'),
        ),
        migrations.AddField(
            model_name='charge',
            name='header',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='charge',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='项目名称'),
        ),
    ]
