# Generated by Django 2.2 on 2019-11-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20191124_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
    ]
