# Generated by Django 2.2 on 2019-11-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20191124_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='contract',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='合同编号'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='header',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='project',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='项目名称'),
        ),
    ]
