# Generated by Django 2.2.7 on 2019-12-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20191124_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='on',
            field=models.BooleanField(choices=[(True, '加班日'), (False, '非加班日')], default=True, verbose_name='是否加班日'),
        ),
    ]
