# Generated by Django 2.2.7 on 2020-02-07 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20191203_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='申请用户组'),
        ),
    ]
